objects-$(CONFIG_LIB_FREEMODBUS_FUNC_USE_COILS)+=mbfunccoils.o
objects-$(CONFIG_LIB_FREEMODBUS_FUNC_USE_DIAG)+=mbfuncdiag.o
objects-$(CONFIG_LIB_FREEMODBUS_FUNC_USE_DISCRETE)+=mbfuncdisc.o
objects-$(CONFIG_LIB_FREEMODBUS_FUNC_USE_HOLDING)+=mbfuncholding.o
objects-$(CONFIG_LIB_FREEMODBUS_FUNC_USE_INPUT)+=mbfuncinput.o
objects-$(CONFIG_LIB_FREEMODBUS_FUNC_USE_OTHER)+=mbfuncother.o
objects-$(CONFIG_LIB_FREEMODBUS_USE_UTILS)+=mbutils.o
